version: '3.9'

services:
  app:
    build: 
      context: .
      args:
        - DEV:TRUE
    ports:
      - '8000:8000'
    volumes:
      - ./App:/App
    command: >
      sh -c 'python manage.py runserver 0.0.0.0.8000'
    
